FROM golang:1.24-alpine

# Install development tools
RUN apk add --no-cache git curl make gcc libc-dev

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Expose HTTP and gRPC ports
EXPOSE 8085 50056

# Set environment variables
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    ENV=development

# Keep the container running
CMD ["tail", "-f", "/dev/null"]
