# Water Classroom Payment Service Configuration
# Default values that can be overridden by environment variables

# Environment
ENV: development

# Server Configuration
SERVER_HOST: 0.0.0.0
SERVER_PORT: 8081
GRPC_PORT: 50052
GRPC_MAX_MESSAGE_SIZE: 4194304  # 4MB

# Logging
LOG_LEVEL: info  # debug, info, warn, error

# Database Configuration
POSTGRES_URI: postgres://postgres:postgres@postgres:5432/water_classroom_payment?sslmode=disable
POSTGRES_MAX_OPEN_CONNS: 25
POSTGRES_MAX_IDLE_CONNS: 25
POSTGRES_CONN_MAX_LIFETIME: 5m

# Redis Configuration
REDIS_ADDR: redis:6379
REDIS_PASSWORD: ""
REDIS_DB: 1
REDIS_POOL_SIZE: 10

# Message Queue
RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/

# Telemetry
OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
OTEL_SERVICE_NAME: payment-service

# CORS Configuration
CORS_ALLOWED_ORIGINS:
  - http://localhost:5173
  - http://localhost:3000

# TLS Configuration (optional)
TLS_CERT_FILE: ""
TLS_KEY_FILE: ""

# Stripe Configuration
STRIPE_SECRET_KEY: "" # Must be set via ENV
STRIPE_PUBLIC_KEY: "" # Must be set via ENV
STRIPE_WEBHOOK_SECRET: "" # Must be set via ENV

# Development Options
MOCK_PAYMENT_PROVIDER: false
