# Air configuration for hot-reloading
# https://github.com/cosmtrek/air

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build the application
cmd = "go build -o ./bin/auth-service ./cmd"
# Binary file produced by the build command
bin = "./bin/auth-service"
# Customize binary
full_bin = "./bin/auth-service"
# Watch these file extensions
include_ext = ["go", "yaml", "yml", "sql"]
# Ignore these directories
exclude_dir = ["bin", "tmp", "vendor", ".git"]
# Ignore these files
exclude_file = []
# Exclude files matching this regex
exclude_regex = ["_test\\.go"]
# Exclude unchanged files
exclude_unchanged = true
# Follow symlinks
follow_symlink = true
# Build delay in milliseconds
delay = 1000
# Stop running old binary when build errors occur
stop_on_error = true
# Send interrupt signal before killing process
send_interrupt = true
# Kill process after this delay (seconds)
kill_delay = 5
# Log build errors
log = "build-errors.log"

[color]
# Customize colors
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
# Show log time
time = true
# Log colors
colors = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
# Clear the screen before each run
clear_on_rebuild = true
# Keep scroll position when the output buffer is cleared
keep_scroll = true
