apiVersion: v2
name: water-classroom
description: Umbrella Helm chart for Water Classroom - AI-Powered Learning Ecosystem
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Stellarium Foundation
    email: hello@stellarium.foundation
home: https://github.com/StellariumFoundation/WaterClassroom
keywords:
  - education
  - ai
  - learning
  - classroom

# Dependencies for all microservices
dependencies:
  - name: auth-svc
    version: 0.1.0
    repository: "file://../auth-svc"
    condition: auth-svc.enabled
    tags:
      - backend
      - auth
  
  - name: user-svc
    version: 0.1.0
    repository: "file://../user-svc"
    condition: user-svc.enabled
    tags:
      - backend
      - user
  
  - name: curriculum-svc
    version: 0.1.0
    repository: "file://../curriculum-svc"
    condition: curriculum-svc.enabled
    tags:
      - backend
      - curriculum
  
  - name: progress-svc
    version: 0.1.0
    repository: "file://../progress-svc"
    condition: progress-svc.enabled
    tags:
      - backend
      - progress
  
  - name: assessment-svc
    version: 0.1.0
    repository: "file://../assessment-svc"
    condition: assessment-svc.enabled
    tags:
      - backend
      - assessment
  
  - name: tutor-orchestrator-svc
    version: 0.1.0
    repository: "file://../tutor-orchestrator-svc"
    condition: tutor-orchestrator-svc.enabled
    tags:
      - backend
      - tutor
  
  - name: notification-svc
    version: 0.1.0
    repository: "file://../notification-svc"
    condition: notification-svc.enabled
    tags:
      - backend
      - notification
  
  - name: api-gateway
    version: 0.1.0
    repository: "file://../api-gateway"
    condition: api-gateway.enabled
    tags:
      - backend
      - gateway

  # Infrastructure dependencies
  - name: postgresql
    version: ~12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - infrastructure
      - database
  
  - name: redis
    version: ~17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - infrastructure
      - cache
  
  - name: rabbitmq
    version: ~12.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
    tags:
      - infrastructure
      - messagequeue
