# Water Classroom - Staging Environment Values
# This file contains the configuration for the staging environment

# Global settings
global:
  environment: staging
  domain: staging.waterclassroom.com
  imagePullPolicy: Always
  
  # Common labels to apply to all resources
  labels:
    environment: staging
    managed-by: helm
  
  # Common annotations
  annotations:
    "meta.helm.sh/release-name": "water-classroom"
    "meta.helm.sh/release-namespace": "water-classroom"

# Enable/disable specific services
tags:
  backend: true
  infrastructure: true

# Service-specific configurations
auth-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-auth-svc
    tag: latest  # Will be overridden by CI/CD pipeline with specific SHA
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  
  env:
    ENV: "staging"
    LOG_LEVEL: "info"
    JWT_ACCESS_TOKEN_EXPIRY: "30m"  # Extended for staging testing
    JWT_REFRESH_TOKEN_EXPIRY: "7d"
    EMAIL_VERIFICATION_REQUIRED: "false"  # Disabled for easier testing in staging
  
  corsConfig:
    allowedOrigins:
      - https://staging.waterclassroom.com
      - http://localhost:5173
      - http://localhost:3000

user-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-user-svc
    tag: latest
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

curriculum-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-curriculum-svc
    tag: latest
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 500m  # More CPU for content generation
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  
  env:
    WEAVIATE_URL: "http://weaviate:8080"

progress-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-progress-svc
    tag: latest
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi

assessment-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-assessment-svc
    tag: latest
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 500m  # More CPU for grading
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

tutor-orchestrator-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-tutor-orchestrator-svc
    tag: latest
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 500m  # More CPU for AI interactions
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  
  env:
    WEAVIATE_URL: "http://weaviate:8080"

notification-svc:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-notification-svc
    tag: latest
  
  replicaCount: 1  # Less critical service
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  env:
    SMTP_HOST: "mailhog"
    SMTP_PORT: "1025"
    SMTP_FROM: "noreply-staging@waterclassroom.com"

api-gateway:
  enabled: true
  image:
    repository: ghcr.io/stellariumfoundation/wc-api-gateway
    tag: latest
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 400m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 128Mi
  
  service:
    type: ClusterIP
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-staging
    hosts:
      - host: api-staging.waterclassroom.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api-staging-tls
        hosts:
          - api-staging.waterclassroom.com
  
  env:
    ENV: "staging"
    LOG_LEVEL: "info"
    AUTH_SERVICE_ADDR: "auth-svc:50051"
    USER_SERVICE_ADDR: "user-svc:50052"
    CURRICULUM_SERVICE_ADDR: "curriculum-svc:50053"
    PROGRESS_SERVICE_ADDR: "progress-svc:50054"
    ASSESSMENT_SERVICE_ADDR: "assessment-svc:50055"
    TUTOR_SERVICE_ADDR: "tutor-orchestrator-svc:50056"
    NOTIFICATION_SERVICE_ADDR: "notification-svc:50057"
  
  corsConfig:
    allowedOrigins:
      - https://staging.waterclassroom.com
      - http://localhost:5173
      - http://localhost:3000

# Infrastructure components
postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres  # Will be overridden by External Secrets in real deployment
    database: water_classroom
  primary:
    persistence:
      size: 10Gi
  metrics:
    enabled: true

redis:
  enabled: true
  auth:
    password: redis  # Will be overridden by External Secrets in real deployment
  master:
    persistence:
      size: 5Gi
  replica:
    replicaCount: 1
    persistence:
      size: 5Gi
  metrics:
    enabled: true

rabbitmq:
  enabled: true
  auth:
    username: guest
    password: guest  # Will be overridden by External Secrets in real deployment
  persistence:
    size: 5Gi
  metrics:
    enabled: true

# Weaviate vector database for AI services
weaviate:
  enabled: true
  image:
    repository: semitechnologies/weaviate
    tag: 1.21
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  
  persistence:
    enabled: true
    size: 10Gi
  
  env:
    QUERY_DEFAULTS_LIMIT: "25"
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    DEFAULT_VECTORIZER_MODULE: "none"
    ENABLE_MODULES: ""

# Observability stack
jaeger:
  enabled: true
  allInOne:
    enabled: true
  collector:
    enabled: false
  agent:
    enabled: false
  query:
    enabled: false
  provisionDataStore:
    cassandra: false
    elasticsearch: false
  storage:
    type: memory  # For staging, use in-memory storage
  
  env:
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"

# External Secrets configuration
externalSecrets:
  enabled: true
  secretStores:
    - name: aws-secretsmanager
      provider: aws
      region: us-west-2

  externalSecrets:
    - name: auth-db-credentials
      secretStore: aws-secretsmanager
      refreshInterval: 1h
      data:
        - key: staging/water-classroom/auth-svc/db
          property: postgres-uri
          name: POSTGRES_URI
    
    - name: auth-redis-credentials
      secretStore: aws-secretsmanager
      refreshInterval: 1h
      data:
        - key: staging/water-classroom/auth-svc/redis
          property: redis-addr
          name: REDIS_ADDR
        - key: staging/water-classroom/auth-svc/redis
          property: redis-password
          name: REDIS_PASSWORD
    
    - name: auth-jwt-keys
      secretStore: aws-secretsmanager
      refreshInterval: 1h
      data:
        - key: staging/water-classroom/auth-svc/jwt
          property: private-key
          name: JWT_PRIVATE_KEY
        - key: staging/water-classroom/auth-svc/jwt
          property: public-key
          name: JWT_PUBLIC_KEY
    
    - name: gemini-api-key
      secretStore: aws-secretsmanager
      refreshInterval: 1h
      data:
        - key: staging/water-classroom/ai/gemini
          property: api-key
          name: GEMINI_API_KEY
