ENV: development
SERVER_HOST: "0.0.0.0" # Added quotes for consistency, though not strictly necessary for this value
SERVER_PORT: "8082"
GRPC_PORT: "50053"
LOG_LEVEL: info
POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/water_classroom?sslmode=disable"
POSTGRES_MAX_OPEN_CONNS: 10
POSTGRES_MAX_IDLE_CONNS: 10
POSTGRES_CONN_MAX_LIFETIME: 5m
