apiVersion: v2
name: auth-svc
description: Authentication Service for Water Classroom - handles user registration, login, JWT issuance, and OAuth
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Stellarium Foundation
    email: hello@stellarium.foundation
home: https://github.com/StellariumFoundation/WaterClassroom
keywords:
  - authentication
  - jwt
  - oauth
  - microservice
  - water-classroom
