# Water Classroom Auth Service Configuration
# Default values that can be overridden by environment variables

# Environment
ENV: development

# Server Configuration
SERVER_HOST: 0.0.0.0
SERVER_PORT: 8080
GRPC_PORT: 50051
GRPC_MAX_MESSAGE_SIZE: 4194304  # 4MB

# Logging
LOG_LEVEL: info  # debug, info, warn, error

# Database Configuration
POSTGRES_URI: postgres://postgres:postgres@postgres:5432/water_classroom?sslmode=disable
POSTGRES_MAX_OPEN_CONNS: 25
POSTGRES_MAX_IDLE_CONNS: 25
POSTGRES_CONN_MAX_LIFETIME: 5m

# Redis Configuration
REDIS_ADDR: redis:6379
REDIS_PASSWORD: ""
REDIS_DB: 0
REDIS_POOL_SIZE: 10

# JWT Configuration
# Note: In production, these should be set via environment variables, not in config
JWT_ACCESS_TOKEN_EXPIRY: 15m
JWT_REFRESH_TOKEN_EXPIRY: 7d
JWT_ISSUER: water-classroom-auth
JWT_AUDIENCE: water-classroom-api

# Password Hashing
PASSWORD_HASH_COST: 12

# Rate Limiting
RATE_LIMIT_REQUESTS: 100
RATE_LIMIT_WINDOW: 1m

# OAuth Providers
# These are placeholders and should be set via environment variables
OAUTH_GOOGLE_CLIENT_ID: ""
OAUTH_GOOGLE_CLIENT_SECRET: ""
OAUTH_GOOGLE_REDIRECT_URL: http://localhost:8080/auth/callback/google

OAUTH_APPLE_CLIENT_ID: ""
OAUTH_APPLE_CLIENT_SECRET: ""
OAUTH_APPLE_REDIRECT_URL: http://localhost:8080/auth/callback/apple

# Message Queue
RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/

# Telemetry
OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
OTEL_SERVICE_NAME: auth-service

# CORS Configuration
CORS_ALLOWED_ORIGINS:
  - http://localhost:5173
  - http://localhost:3000

# TLS Configuration (optional)
TLS_CERT_FILE: ""
TLS_KEY_FILE: ""

# Email Verification
EMAIL_VERIFICATION_REQUIRED: true
EMAIL_VERIFICATION_TOKEN_EXPIRY: 24h

# Account Recovery
PASSWORD_RESET_TOKEN_EXPIRY: 1h

# Development Options (never enable in production)
DISABLE_AUTH: false
