name: Docker Image CI

on:
  push:
    branches: [ "master", "Development"]
  pull_request:
    branches: [ "master",  "Development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24' # Specify your Go version

    - name: Run backend tests
      working-directory: backend
      run: make test

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify your Node.js version, adjust if needed

    - name: Install frontend dependencies and run tests
      working-directory: frontend
      run: |
        make test # This should handle npm install and npm test as per frontend/Makefile

    # Note: The frontend is built here, but its static assets are not currently
    # included in the Docker image built in the subsequent step.
    # The Dockerfile would need to be modified to include these assets
    # if the goal is a self-contained application image.
    - name: Build frontend
      working-directory: frontend
      run: make build # This should handle npm install and vite build as per frontend/Makefile

    # Note: This Docker build currently only includes the backend application.
    # Frontend assets built in previous steps are not packaged into this image.
    - name: Build the Docker image (Backend)
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
